/*
 * @lc app=leetcode id=389 lang=csharp
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (52.77%)
 * Total Accepted:    138.4K
 * Total Submissions: 262K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 */
public class Solution {
    public char FindTheDifference(string s, string t) {
        Dictionary<char, int> dic = new Dictionary<char, int>();
        for (int i = 0; i < s.Length; i++)
        {
            int n;
            if(!dic.TryGetValue(s[i], out n)){
                n = 0;
            }
            dic[s[i]] = n+1;
        }

        for (int i = 0; i < t.Length; i++)
        {
            int n;
            if(!dic.TryGetValue(t[i], out n)){
                return t[i];
            }
            
            if(n<=1)
                dic.Remove(t[i]);
            else
                dic[t[i]] = n-1;

        }
        return '\0';
    }
}


// √ Accepted
//   √ 54/54 cases passed (92 ms)
//   √ Your runtime beats 100 % of csharp submissions
//   √ Your memory usage beats 76.19 % of csharp submissions (22.6 MB)
